### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by danielcompton** [JarvusInnovations/background-action#170]
Hi there

I tried this out on a project and got this error:

```
Run JarvusInnovations/background-action@c44874fd82200490d31d804b7270350705582a23
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/JarvusInnovations/background-action/c44874fd82200490d31d804b7270350705582a23/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/_actions/JarvusInnovations/background-action/c44874fd82200490d31d804b7270350705582a23/index.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/JarvusInnovations/background-action/c44874fd82200490d31d804b7270350705582a23/index.js'
  ]
}
```

With this config, mostly copied from the README.

```yaml
      - uses: JarvusInnovations/background-action@c44874fd82200490d31d804b7270350705582a23 # v1.0.3
        name: Bootstrap System Under Test (SUT)
        with:
          run: |
            script/server &

          wait-on: |
            http://localhost:4274

          tail: true # true = stderr,stdout

          log-output-resume: stderr
          # Eliminates previosuly output stderr log entries from post-run output

          wait-for: 1m

          log-output: stderr,stdout # same as true

          log-output-if: failure
          # failure = exit-early or timeout

          working-directory: renderer
          # sets the working directory (cwd) for the shell running commands
```

I tried installing @actions/core into my own project but that didn't work. Is there more here that I need to do?
