### ISSUE TITLE
Post-job Log Output: Improve Error Handling for ENOENT in complex workflows

### ISSUE THREAD

**Issue by vera** [JarvusInnovations/background-action#187]
Hi, I am running this action in my pipeline:

```
      - name: Forward ports using kubectl
        uses: JarvusInnovations/background-action@v1.0.5
        with:
          run: |
            kubectl port-forward mypod1 8080:8080 &
            kubectl port-forward mypod2 9200:9200 &
          wait-on: http://localhost:8080/api/info/version
```

The post job "Post Forward ports using kubectl" fails the pipeline with the following error message:

```
Post job cleanup.
Output:
Error: ENOENT: no such file or directory, open '/home/runner/work/myrepo/myrepo/1646.out
```

Any idea why this could happen? Thank you!
