### ISSUE TITLE
Add delay and interval options

### ISSUE THREAD

**Issue by joh-klein** [JarvusInnovations/background-action#204]
Would you consider adding `delay` and `interval` options? Or could you maybe show a minimal JSON input with these two options set?

Thank you! I really appreciate your action!

**Comment by gabrielf** [comment]
Here is an example where `wait-on` is configured using JSON:


```yaml
      - uses: JarvusInnovations/background-action@v1
        name: Example background action with advanced wait-on config
        with:
          run: |
            npm install && npm start

          wait-on: |
            {
              "resources": [
                "http://localhost:${{ env.API_PORT }}",
                "http-get://localhost:2121",
                "tcp:localhost:3232",
                "file://very-important-secrets.txt"
              ],
              "simultaneous": 1,
              "delay": 10000,
              "interval": 1000,
              "timeout": 300000
             }

          wait-for: 5m
```

Note that `delay`, `interval`, `timeout` are set in milliseconds.
